export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees ',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getti ng charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-33.png'),
    alt: 'Money',
    dark: true,
    primary: true,
    darkText: false,
};